### ISSUE TITLE
Bundle analyzer API throwing 500 internal server error

### ISSUE THREAD

**Issue by Arcticae** [smooth-code/bundle-analyzer#28]
```
{
  "message": "Request failed with status code 500",
  "name": "Error",
  "stack": "Error: Request failed with status code 500\n    at createError (/Volumes/Case Sensitive Partition/wielki-janusz/web/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Volumes/Case Sensitive Partition/wielki-janusz/web/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Volumes/Case Sensitive Partition/wielki-janusz/web/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:333:22)\n    at endReadableNT (_stream_readable.js:1201:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "config": {
    "url": "https://api.bundle-analyzer.com/builds",
    "method": "post",
    "data": "{\"token\":\"<TOKEN_HERE>\",\"bundleId\":\"1edc84e9-1fcb-4b32-aded-d054669be965\",\"branch\":\"feature/mini-switch-styles\",\"commit\":\"69ec234d19814dc5b12d24ff5244f234e9a3658b\",\"providerMetadata\":{\"name\":\"git\",\"commit\":\"69ec234d19814dc5b12d24ff5244f234e9a3658b\",\"branch\":\"feature/mini-switch-styles\"},\"config\":null}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8",
      "User-Agent": "axios/0.19.2",
      "Content-Length": 330
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  }
}
```
The api keeps 500ing on some of my builds for some of branches. Other branches seem to be fine. Can provide additional debug info if needed.

**Comment by gregberge** [comment]
Hello @Arcticae, this is actually a bug. Unfortunately I don't have so much time to take care of the project right now. I received two sentries on the project:

<img width="1085" alt="Screenshot 2020-03-07 at 14 39 24" src="https://user-images.githubusercontent.com/266302/76144506-7d73a500-6081-11ea-9192-786ded070700.png">
<img width="1073" alt="Screenshot 2020-03-07 at 14 39 32" src="https://user-images.githubusercontent.com/266302/76144508-7ea4d200-6081-11ea-9d74-18a410d10fd9.png">

Maybe it could help someone to debug it.

**Comment by jlopezxs** [comment]
The author id would be optional, because you can commit with a git user without GitHub user.

**Comment by gregberge** [comment]
Hello @jlopezxs if you are interested to be involved in the project, I could give you keys to be able to work on the project. Feel free to reach me by email.

**Comment by a-axton** [comment]
For anyone wondering how to fix this without a code change, just make sure that `git config --global user.email` is the same as your github account email.

It's easy to find these users because it will have two different accounts on commit messages, one will be the git account with no profile link and an anonymous profile pic the other would be the actual github account
![image](https://user-images.githubusercontent.com/4015654/83806851-f7a6cc00-a666-11ea-8202-27b9ecf1c22c.png)

**Comment by gregberge** [comment]
Hello, I actually don't have time to maintain this project, I am looking for maintainers.
