### ISSUE TITLE
Bundle analyzer randomly failing with 503

### ISSUE THREAD

**Issue by thedotedge** [smooth-code/bundle-analyzer#33]
Not sure if it's related to https://github.com/smooth-code/bundle-analyzer/issues/28, since status code it 503 and not 500. Those cases it does not fail, it takes significant time (up to 120 seconds, while without bundle analyzer it takes up to 20 seconds). 

```
> npx webpack --config webpack.ci.js "--env.BUNDLE_ANALYZER_TOKEN=****************************************"
 
Error: Bundle Analyzer - Request failed with status code 503
    at /app/node_modules/@bundle-analyzer/webpack-plugin/lib/index.js:32:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 ```

**Comment by gregberge** [comment]
Hello, I actually don't have time to maintain this project, I am looking for maintainers.
